### ISSUE TITLE
An old version of MySQL is used and is not implemented in a scalable manner

### ISSUE THREAD

**Issue by jrodel17** [aau-giraf/giraf-production-swarm#10]
An upgrade to a newer LTS of MySQL should be considered or potentially a migration to PostgreSQL, which as of now adhere to the SQL standards, which MySQL. This should likely be considered and might constitute several related issues when decided upon. Furthermore, I was informed by the people working on the project from last year, that currently the MySQL image is not deployed in a scalable manner like the rest of the images in the docker swarm, which means that there is no backup if the instance running the MySQL shuts down.

Note: The template script didn't really match this issue

**Comment by jrodel17** [comment]
Note! The API might need to be refactored if the database is updated, especially if it is changed to postgreSQL.

**Comment by Seraph2** [comment]
In terms of EOL, MySQL 8.0 ends at April, 2026, while PostgreSQL 12.2 ends at November 14, 2024. However MySQL 5.7 ends at October 21, 2023 which is still quite a lot of time until its end-of-life. Although I feel it is better to stick to MySQL because of: Longer lifespan, and moving to PostgreSQL might be more difficult to do (especially as PostgreSQL will require different libraries).

**Comment by Lortemanden** [comment]
Group 16 has worked with this in sprint 1.
They have done some research. They can update the current version but is still working on making it scalable.  
Group 16 would like to work with this in sprint 2.
